# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ToolsWindowCopy import Ui_TechWindow
from SearchScreenCopy import Ui_SearchScreen
from UserSearchScreen import Ui_UserSearchScreen
from Baza import Baza
import cgitb

cgitb.enable(format='text')

class Ui_LoginScreen(object):
    def __init__(self, base):
        self.dtbase = base

    def setupUi(self, LoginScreen):
        LoginScreen.setObjectName("LoginScreen")
        LoginScreen.resize(403, 165)

        self.centralwidget = QtWidgets.QWidget(LoginScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Identyfikator = QtWidgets.QLabel(self.centralwidget)
        self.label_Identyfikator.setGeometry(QtCore.QRect(10, 40, 71, 16))
        self.label_Identyfikator.setObjectName("label_Identyfikator")
        self.label_Haslo = QtWidgets.QLabel(self.centralwidget)
        self.label_Haslo.setGeometry(QtCore.QRect(40, 79, 31, 16))
        self.label_Haslo.setObjectName("label_Haslo")
        self.Text_Identyfikator = QtWidgets.QTextEdit(self.centralwidget)
        self.Text_Identyfikator.setGeometry(QtCore.QRect(90, 40, 151, 21))
        self.Text_Identyfikator.setObjectName("Text_Identyfikator")
        self.Text_Haslo = QtWidgets.QTextEdit(self.centralwidget)
        self.Text_Haslo.setGeometry(QtCore.QRect(90, 80, 151, 21))
        self.Text_Haslo.setObjectName("Text_Haslo")
        self.Guzik_Logujacy = QtWidgets.QPushButton(self.centralwidget)
        self.Guzik_Logujacy.setGeometry(QtCore.QRect(290, 80, 75, 23))
        self.Guzik_Logujacy.setObjectName("Guzik_Logujacy")
        LoginScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 403, 21))
        self.menubar.setObjectName("menubar")
        LoginScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginScreen)
        self.statusbar.setObjectName("statusbar")
        LoginScreen.setStatusBar(self.statusbar)

        # okienko do wyświetlania powiadomień
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 110, 300, 26))
        self.textBrowser.setObjectName("textBrowser")


        self.retranslateUi(LoginScreen)
        QtCore.QMetaObject.connectSlotsByName(LoginScreen)


    def retranslateUi(self, LoginScreen):
        _translate = QtCore.QCoreApplication.translate
        LoginScreen.setWindowTitle(_translate("LoginScreen", "MainWindow"))
        self.label_Identyfikator.setText(_translate("LoginScreen", "Identyfikator:"))
        self.label_Haslo.setText(_translate("LoginScreen", "Hasło:"))
        self.Guzik_Logujacy.setText(_translate("LoginScreen", "Login"))

        self.textBrowser.setText('Zaloguj się swoim peselem')

        self.Guzik_Logujacy.clicked.connect(self.getChoice)

    def getChoice(self):
        try:
            pesele = Baza.selectPesels(self.dtbase)
            pesele2 = []
            for i in pesele:
                pesele2.append(int(i[0]))

            passwd = self.Text_Haslo.toPlainText()
            idd = self.Text_Identyfikator.toPlainText()

            if passwd == "admin" and idd == "admin":
                self.TechWindow1 = QtWidgets.QMainWindow()
                self.TechWindow3 = QtWidgets.QMainWindow()

                self.ui1 = Ui_TechWindow(self.dtbase)
                self.ui3 = Ui_SearchScreen(self.dtbase)

                self.ui1.setupUi(self.TechWindow1)
                self.ui3.setupUi(self.TechWindow3)


                self.TechWindow1.show()
                self.TechWindow3.show()

            elif passwd == idd and int(idd) in pesele2:
                self.TechWindow1 = QtWidgets.QMainWindow()

                self.ui1 = Ui_UserSearchScreen(self.dtbase, int(idd))

                self.ui1.setupUi(self.TechWindow1)

                self.TechWindow1.show()
            else:
                self.textBrowser.setText('Zły login albo hasło')
        except:
            print('cuśik poszedu nie tak przy logowaniu')
        # return item1, item2, item3
