# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserSearchScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Baza import Baza
import traceback
import cgitb

cgitb.enable(format='text')

class Ui_UserSearchScreen(object):
    def __init__(self, base, psl):
        self.dtbase = base
        self.pesel = psl

    def setupUi(self, UserSearchScreen):
        UserSearchScreen.setObjectName("UserSearchScreen")
        UserSearchScreen.resize(900, 500)
        self.centralwidget = QtWidgets.QWidget(UserSearchScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Relacja = QtWidgets.QLabel(self.centralwidget)
        self.label_Relacja.setGeometry(QtCore.QRect(30, 20, 47, 13))
        self.label_Relacja.setObjectName("label_Relacja")
        self.wybor_Relacji = QtWidgets.QListWidget(self.centralwidget)
        self.wybor_Relacji.setGeometry(QtCore.QRect(20, 40, 200, 120))
        self.wybor_Relacji.setObjectName("wybor_Relacji")


        #okienko do wyświetlania powiadomień
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 250, 256, 192))
        self.textBrowser.setObjectName("textBrowser")





        self.label_Wyszukiwanie = QtWidgets.QLabel(self.centralwidget)
        self.label_Wyszukiwanie.setGeometry(QtCore.QRect(30, 170, 91, 16))
        self.label_Wyszukiwanie.setObjectName("label_Wyszukiwanie")
        self.Tablica_Wynikow = QtWidgets.QTableWidget(self.centralwidget)
        self.Tablica_Wynikow.setGeometry(QtCore.QRect(300, 40, 600, 331))
        self.Tablica_Wynikow.setObjectName("Tablica_Wynikow")


        self.Tablica_Wynikow.setColumnCount(10)
        for i in range(10):
            item = QtWidgets.QTableWidgetItem()
            self.Tablica_Wynikow.setHorizontalHeaderItem(i, item)


        self.Tablica_Wynikow.setRowCount(30)
        for i in range(30):
            item = QtWidgets.QTableWidgetItem()
            self.Tablica_Wynikow.setVerticalHeaderItem(i, item)

        self.Guzik_Zatwierdzajacy = QtWidgets.QPushButton(self.centralwidget)
        self.Guzik_Zatwierdzajacy.setGeometry(QtCore.QRect(700, 400, 75, 23))
        self.Guzik_Zatwierdzajacy.setObjectName("Guzik_Zatwierdzajacy")





        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setStrikeOut(False)
        item.setFont(font)

        self.label_Wynik = QtWidgets.QLabel(self.centralwidget)
        self.label_Wynik.setGeometry(QtCore.QRect(320, 20, 151, 16))
        self.label_Wynik.setObjectName("label_Wynik")
        UserSearchScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UserSearchScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 549, 21))
        self.menubar.setObjectName("menubar")
        UserSearchScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UserSearchScreen)
        self.statusbar.setObjectName("statusbar")
        UserSearchScreen.setStatusBar(self.statusbar)




        self.retranslateUi(UserSearchScreen)
        QtCore.QMetaObject.connectSlotsByName(UserSearchScreen)

    def retranslateUi(self, UserSearchScreen):
        _translate = QtCore.QCoreApplication.translate
        UserSearchScreen.setWindowTitle(_translate("UserSearchScreen", "MainWindow"))
        self.label_Relacja.setText(_translate("UserSearchScreen", "Relacja:"))
        __sortingEnabled = self.wybor_Relacji.isSortingEnabled()
        self.wybor_Relacji.setSortingEnabled(False)

        for i in range(2):
            item = QtWidgets.QListWidgetItem()
            self.wybor_Relacji.addItem(item)

        # Ustawienie listy relacji do wyboru
        item = self.wybor_Relacji.item(0)
        item.setText(_translate("UserSearchScreen", 'Twoje dane osobowe'))
        item = self.wybor_Relacji.item(1)
        item.setText(_translate("UserSearchScreen", 'Wszystkie donacje'))

        self.Guzik_Zatwierdzajacy.setText(_translate("TechWindow", "Zatwierdź"))


        self.wybor_Relacji.setSortingEnabled(__sortingEnabled)

        self.label_Wynik.setText(_translate("UserSearchScreen", "Wynik wyszukiwania:"))

        self.wybor_Relacji.clicked.connect(self.UpdateWyniki)

    def UpdateWyniki(self):
        item1 = self.wybor_Relacji.currentItem()
        item1 = item1.text()

        _translate = QtCore.QCoreApplication.translate


        if item1 == 'Twoje dane osobowe':
            try:
                xd = Baza.selectuserInfo(self.dtbase, self.pesel)
                if xd is not None:

                    for c in range(len(xd[0])):
                        item = self.Tablica_Wynikow.horizontalHeaderItem(c)
                        item.setText(_translate("TechWindow", 'bob'))
                        item1 = QtWidgets.QTableWidgetItem()
                        self.Tablica_Wynikow.setItem(0, c, item1)
                        item = self.Tablica_Wynikow.item(0, c)
                        item.setText(_translate("TechWindow", str(xd[0][c])))
            except Exception:
                traceback.print_exc()
                print('coś nie tak w klikaniu w dane osobowe')
                self.textBrowser.setText('coś nie tak w klikaniu w dane osobowe')
        elif item1 == 'Wszystkie donacje':
            try:
                xd = Baza.selectuserWszystkieDonacje(self.dtbase, self.pesel)
                print(xd)
                if xd is not None:

                    for c in range(len(xd[0])):
                        item = self.Tablica_Wynikow.horizontalHeaderItem(c)
                        item.setText(_translate("TechWindow", 'bob'))
                        item1 = QtWidgets.QTableWidgetItem()
                        self.Tablica_Wynikow.setItem(0, c, item1)
                        item = self.Tablica_Wynikow.item(0, c)
                        item.setText(_translate("TechWindow", str(xd[0][c])))
            except Exception:
                traceback.print_exc()
                print('coś nie tak w klikaniu w dane osobowe')

        print('what is')
